name: Build Cpp By CMake

on:
  [ push,pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: cpp-test
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest,windows-latest,macos-latest ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code
        uses: actions/checkout@v2

      - name: ensure the cmake
        run: cmake --version

      - name: prepare folder
        run: cmake -E make_directory ./CMAKE_DEBUG_PATH

      - name: cmake prepare for compile
        working-directory: ./CMAKE_DEBUG_PATH
        run: cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: cmake prepare for compile
        working-directory: ./CMAKE_DEBUG_PATH
        run: cmake --build . --config Release

      - name: cmake ctest
        working-directory: ./CMAKE_DEBUG_PATH
        run: ctest

